In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("C:\\Users\\user\\Desktop\\data sets\\Attrition.csv")

In [3]:
df.head()

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   
4   27        No      Travel_Rarely        591  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   
4                 2          1        Medical              1               7   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   
4  ...                         4            80                 1   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   
4                  6                      3               3               2   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  
4                  2                        2                     2  

[5 rows x 35 columns]

In [4]:
import tensorflow as tf 
from sklearn.model_selection import train_test_split

In [5]:
from sklearn.preprocessing import LabelEncoder , StandardScaler

In [6]:
from sklearn.metrics import accuracy_score

In [7]:
df = df.dropna()

In [8]:
x = df.drop(columns = 'Attrition', axis = 1)
y = df["Attrition"]

In [9]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   BusinessTravel            1470 non-null   object
 2   DailyRate                 1470 non-null   int64 
 3   Department                1470 non-null   object
 4   DistanceFromHome          1470 non-null   int64 
 5   Education                 1470 non-null   int64 
 6   EducationField            1470 non-null   object
 7   EmployeeCount             1470 non-null   int64 
 8   EmployeeNumber            1470 non-null   int64 
 9   EnvironmentSatisfaction   1470 non-null   int64 
 10  Gender                    1470 non-null   object
 11  HourlyRate                1470 non-null   int64 
 12  JobInvolvement            1470 non-null   int64 
 13  JobLevel                  1470 non-null   int64 
 14  JobRole                 

In [10]:
#Preprocessing categorical data
categroical_features = ['BusinessTravel','Department','EducationField','Gender','JobRole','MaritalStatus','Over18',
                       'OverTime']

In [11]:
x_encoded = pd.get_dummies(x,columns = categroical_features, drop_first = True )

In [12]:
# Encode target column
lb = LabelEncoder()
y_encoded = lb.fit_transform(y)
y_encoded

array([1, 0, 1, ..., 0, 0, 0])

In [13]:
x_train,x_test, y_train,y_test = train_test_split(x_encoded,y_encoded,test_size=0.2 , random_state=9)

In [14]:
sc = StandardScaler()

In [15]:
x_train_scaled = sc.fit_transform(x_train)
x_test_scaled = sc.transform(x_test)

# Now we will create architexture of our model

In [16]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units = 128 , activation = 'relu', input_dim = x_train_scaled.shape[1]),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units = 64 , activation='relu'),
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units = 1 , activation='sigmoid')
])

In [17]:
# Define loss function and metris 
loss_fn = tf.keras.losses.BinaryCrossentropy()
metrics = ['accuracy']


In [18]:
# Define loss function and metrics 
learning_rate = 0.001
mometum = 0.9
optimizer = tf.keras.optimizers.SGD(learning_rate = learning_rate, momentum=mometum, nesterov=True)

In [19]:
# Compile the model
model.compile(optimizer= optimizer, loss =loss_fn , metrics = metrics)
model.fit(x_train_scaled, y_train, epochs = 50 , batch_size = 8 , validation_split= 0.1)

Epoch 1/50
133/133 [==============================] - 2s 6ms/step - loss: 0.5052 - accuracy: 0.8006 - val_loss: 0.5115 - val_accuracy: 0.8051
Epoch 2/50
133/133 [==============================] - 0s 3ms/step - loss: 0.4387 - accuracy: 0.8403 - val_loss: 0.4749 - val_accuracy: 0.8051
Epoch 3/50
133/133 [==============================] - 0s 3ms/step - loss: 0.4153 - accuracy: 0.8431 - val_loss: 0.4543 - val_accuracy: 0.8051
Epoch 4/50
133/133 [==============================] - 0s 3ms/step - loss: 0.4130 - accuracy: 0.8459 - val_loss: 0.4342 - val_accuracy: 0.8220
Epoch 5/50
133/133 [==============================] - 0s 3ms/step - loss: 0.3872 - accuracy: 0.8478 - val_loss: 0.4216 - val_accuracy: 0.8305
Epoch 6/50
133/133 [==============================] - 0s 3ms/step - loss: 0.3747 - accuracy: 0.8497 - val_loss: 0.4160 - val_accuracy: 0.8305
Epoch 7/50
133/133 [==============================] - 0s 3ms/step - loss: 0.3696 - accuracy: 0.8563 - val_loss: 0.4096 - val_accuracy: 0.8390
Epoch 

In [20]:
# Evaluate the model on test set 
loss ,accuracy = model.evaluate(x_test_scaled , y_test)
print(f"Test loss ={loss:4f}, Test Accuracy = {accuracy : 4f}")

10/10 [==============================] - 0s 2ms/step - loss: 0.3330 - accuracy: 0.8980
Test loss =0.332961, Test Accuracy =  0.897959


In [23]:
predictions = model.predict(x_test_scaled)
predictions

10/10 [==============================] - 0s 2ms/step


array([[8.04752053e-04],
       [3.25935520e-02],
       [3.93057652e-02],
       [8.76896549e-03],
       [1.13001930e-04],
       [1.52664661e-01],
       [3.85818511e-01],
       [3.17167863e-03],
       [8.39588977e-03],
       [1.70305714e-01],
       [2.15286076e-01],
       [3.67444716e-02],
       [7.01089902e-03],
       [3.31186503e-02],
       [9.54970777e-01],
       [3.99267338e-02],
       [6.41912401e-01],
       [5.57212370e-05],
       [5.55255450e-02],
       [2.86651272e-02],
       [1.20119443e-02],
       [1.81770414e-01],
       [8.39798212e-01],
       [1.00160867e-01],
       [1.77013886e-03],
       [2.62115031e-01],
       [5.76657295e-01],
       [2.19778419e-02],
       [1.24269314e-01],
       [8.64787400e-02],
       [4.85194672e-04],
       [9.38635785e-03],
       [3.32580924e-01],
       [5.53939164e-01],
       [3.77019010e-02],
       [9.21441894e-03],
       [2.48651564e-01],
       [1.64176561e-02],
       [4.05529179e-02],
       [1.29997460e-02],


In [25]:
prediction_labels = (predictions>0.5).astype(int)
prediction_labels

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
    